apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: srpl/server-side:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://<DB_ADDRESS>:5432/<DB_NAME>
        - name: SPRING_DATASOURCE_USERNAME
          value: <USERNAME>
        - name: SPRING_DATASOURCE_PASSWORD
          value: <PASSWORD>
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
